project:
  type: site

execute:
  freeze: auto

site:
  title: "RStudio Workbench Administration"
  #  subtitle: "Version ${CPACK_PACKAGE_VERSION}"
  #  date: "${TODAY}"
  #  output-file: "rstudio-server-pro-${CPACK_PACKAGE_VERSION}-admin-guide"
  downloads: [docx, pdf, epub]
  sharing: [twitter, facebook, linkedin]
  page-navigation: true
  site-url: https://docs.rstudio.com/ide/server-pro/
  repo-url: https://github.com/rstudio/rstudio/
  sidebar:
    logo: images/logo.png
    style: "docked"
    background: light
    search: true
    collapse-level: 1
    align: left
    contents:
      - section: "Getting Started"
        href: index.qmd
        contents:
          - getting_started/installation.qmd
          - getting_started/management_script.qmd
          - getting_started/activation.qmd
          - getting_started/accessing_the_server.qmd
          - getting_started/community_resources.qmd
          - getting_started/professional_support.qmd
      - section: "Server Management"
        href: server_management/server_management.qmd
        contents:
          - server_management/core_administrative_tasks.qmd
          - server_management/logging.qmd
          - server_management/administrative_dashboard.qmd
          - server_management/automated_crash_reporting.qmd
      - section: "Authenticating Users"
        href: authenticating_users/authenticating_users.qmd
        contents:
          - authenticating_users/user_provisioning.qmd
          - authenticating_users/pam_basics.qmd
          - authenticating_users/authentication_migration.qmd
          - authenticating_users/pam_authentication.qmd
          - authenticating_users/restricting_access.qmd
          - authenticating_users/saml_sso.qmd
          - authenticating_users/openid_connect_authentication.qmd
          - authenticating_users/proxied_authentication.qmd
          - authenticating_users/google_accounts.qmd
          - authenticating_users/customizing_signin.qmd
          - authenticating_users/authorization_timeout.qmd
      - section: "Access and Security"
        href: access_and_security/access_and_security.qmd
        contents:
          - access_and_security/network_port_and_address.qmd
          - access_and_security/ip_access_rules.qmd
          - access_and_security/frame_origin.qmd
          - access_and_security/same_site_cookies.qmd
          - access_and_security/compatibility_with_safari.qmd
          - access_and_security/additional_security_considerations.qmd
          - access_and_security/additional_headers.qmd
          - access_and_security/secure_sockets.qmd
          - access_and_security/ssl_ports.qmd
          - access_and_security/cookies.qmd
          - access_and_security/server_permissions.qmd
          - access_and_security/running_with_a_proxy.qmd
      - section: "R Sessions"
        href: r_sessions/r_sessions.qmd
        contents:
          - r_sessions/r_executable_and_libraries.qmd
          - r_sessions/session_startup_scripts.qmd
          - r_sessions/user_and_group_profiles.qmd
          - r_sessions/multiple_r_sessions.qmd
          - r_sessions/pam_sessions.qmd
          - r_sessions/kerberos.qmd
          - r_sessions/directory_management.qmd
          - r_sessions/workspace_management.qmd
          - r_sessions/first_project_template.qmd
          - r_sessions/project_sharing.qmd
          - r_sessions/package_installation.qmd
          - r_sessions/feature_limits.qmd
          - r_sessions/notifications.qmd
          - r_sessions/rstudio_connect_server.qmd
          - r_sessions/terminal_websockets.qmd
          - r_sessions/customizing_session_settings.qmd
      - section: "R Versions"
        href: r_versions/r_versions.qmd
        contents:
          - r_versions/installing_r.qmd
          - r_versions/configuring_default.qmd
          - r_versions/using_multiple_versions_of_r.qmd
          - r_versions/managing_upgrades.qmd
          - r_versions/session_initialization.qmd
      - section: "Load Balancing"
        href: load_balancing/load_balancing.qmd
        contents:
          - load_balancing/load_balancing_vs_job_launcher.qmd
          - load_balancing/configuration.qmd
          - load_balancing/access_and_availability.qmd
          - load_balancing/balancing_methods.qmd
      - section: "Auditing and Monitoring"
        href: auditing_and_monitoring/auditing_and_monitoring.qmd
        contents:
          - auditing_and_monitoring/auditing_configuration.qmd
          - auditing_and_monitoring/monitoring_configuration.qmd
          - auditing_and_monitoring/server_health_checks.qmd
      - section: "License Management"
        href: license_management/license_management.qmd
        contents:
          - license_management/product_activation.qmd
          - license_management/license_details.qmd
          - license_management/connectivity_requirements.qmd
          - license_management/evaluations.qmd
          - license_management/floating_licensing.qmd
          - license_management/userspace_licensing.qmd
      - section: "Data Connectivity"
        href: data_connectivity/data_connectivity.qmd
        contents:
          - data_connectivity/connectivity_using_odbc.qmd
          - data_connectivity/connectivity_using_r_packages.qmd
          - data_connectivity/snippet_files.qmd
      - section: "Job Launcher"
        href: job_launcher/job_launcher.qmd
        contents:
          - job_launcher/configuration.qmd
          - job_launcher/running_the_launcher.qmd
          - job_launcher/load_balancing.qmd
          - job_launcher/creating_plugins.qmd
          - job_launcher/troubleshooting.qmd
      - section: "Tutorial API"
        href: tutorial_api/tutorial_api.qmd
        contents:
          - tutorial_api/configuration.qmd
          - tutorial_api/interface.qmd
          - tutorial_api/tutorial_api_methods.qmd
          - tutorial_api/tutorial_api_callbacks.qmd
      - section: "Jupyter Sessions"
        href: jupyter_sessions/jupyter_sessions.qmd
        contents:
          - jupyter_sessions/configuration.qmd
          - jupyter_sessions/troubleshooting.qmd
      - section: "VS Code Sessions"
        href: vscode_sessions/vs_code_sessions.qmd
        contents:
          - vscode_sessions/installation.qmd
          - vscode_sessions/configuration.qmd
          - vscode_sessions/multiple_sessions.qmd
          - vscode_sessions/troubleshooting.qmd
      - section: "Database"
        href: database/database.qmd
        contents:
          - database/configuration.qmd
          - database/migration.qmd
      - section: "Hardening"
        href: hardening/hardening.qmd
        contents:
          - hardening/set_up_ssl.qmd
          - hardening/browser_security.qmd
          - hardening/r_session_security.qmd
          - hardening/other.qmd
          - hardening/example_secure_configuration.qmd
      - section: "Session User Settings"
        href: session_user_settings/session_user_settings.qmd
      - section: "R Studio IDE Commands"
        href: rstudio_ide_commands/rstudio_ide_commands.qmd
      - section: "R Package Dependencies"
        href: r_package_dependencies/r_package_dependencies.qmd
      - section: "R Studio Configuration"
        href: rstudio_server_configuration/rstudio_server_configuration.qmd
        contents:
          - rstudio_server_configuration/rserver_conf.qmd
          - rstudio_server_configuration/rsession_conf.qmd


number-depth: 2

format:
  html:
    theme: cosmo
    css: styles/guide.css
    include-in-header: google_analytics.html
    toc: true
